server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_ead_course
    username: postgres
    password: ${PASSWORD_POSTGRES}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true